"""Compatibility re-export for the import-safe format layer."""

from ..frontmatter_utils import (
    PROJECT_COLD_START_HEADINGS,
    add_progress_log_row,
    append_plan_to_summary,
    build_plan_summary_block,
    build_project_cold_start_sections,
    collect_project_cold_start_signals,
    collect_project_entries,
    count_active_project_plans,
    count_project_plans,
    extract_project_cold_start_sections,
    find_begin_end_block,
    find_section_bounds,
    infer_section_id_from_path,
    infer_subject_from_path,
    insert_entry_in_section,
    mark_plan_item_complete,
    parse_plan_items,
    read_with_frontmatter,
    remove_entry_from_section,
    render_projects_navigator,
    replace_begin_end_block,
    today_str,
    update_frontmatter_fields,
    write_with_frontmatter,
)

__all__ = [
    "PROJECT_COLD_START_HEADINGS",
    "add_progress_log_row",
    "append_plan_to_summary",
    "build_plan_summary_block",
    "build_project_cold_start_sections",
    "collect_project_cold_start_signals",
    "collect_project_entries",
    "count_active_project_plans",
    "count_project_plans",
    "extract_project_cold_start_sections",
    "find_begin_end_block",
    "find_section_bounds",
    "infer_section_id_from_path",
    "infer_subject_from_path",
    "insert_entry_in_section",
    "mark_plan_item_complete",
    "parse_plan_items",
    "read_with_frontmatter",
    "remove_entry_from_section",
    "render_projects_navigator",
    "replace_begin_end_block",
    "today_str",
    "update_frontmatter_fields",
    "write_with_frontmatter",
]
